---
#--------------------------------------------------
# This playbook will upgrade the Docker containers on the CAM hosts
# based on the variables set
#--------------------------------------------------

- name: Upgrade CAM host Docker Containers
  hosts: localhost
  gather_facts: true
  
  vars:
#--------------------------------------------------
# Change these vars to 'true' to upgrade the container

  - upg_gitlab: false    
  - upg_slmansible: false
  - upg_slmpuppet: true
  - upg_slmsamba: true
  - upg_slamio: true
  - upg_slmzsync: true

  - docker_projects:
      - { upg: "{{ upg_gitlab }}", image: gitlab/gitlab-ce, name: , key: }
      - { upg: "{{ upg_slmansible }}", image: slmansible, name: ansible-sandbox, key: slm_ansible_sandbox_ro_deployment_key_rsa }
      - { upg: "{{ upg_slmpuppet }}", image: slmpuppet, name: docker-slmpuppet, key: slm_slmpuppet_ro_deployment_key_rsa }
      - { upg: "{{ upg_slmsamba }}", image: slmsamba, name: docker-slmsamba, key: slm_slmsamba_ro_deployment_key_rsa }
      - { upg: "{{ upg_slamio }}", image: slamio, name: docker-mediacascade, key: slamio_ro_deployment_key_rsa }
      - { upg: "{{ upg_slmzsync }}", image: slmzsync, name: docker-mediacascade, key: slm_mediacascade_ro_deployment_key_rsa }

  tasks:

#    - name: Upgrade Docker Containers from repos
#      block: 

    - name: Remove existing project from /opt/csc/src
      file: 
        path: /opt/csc/src/{{ item.name }}
        state: absent
      with_items: "{{ docker_projects }}"
      when: item.upg and item.name is defined

#    - name: Remove existing Docker image
#      docker_image:
#        name: "{{ item.image }}"
#        state: absent
#      with_items: "{{ docker_projects }}"
#      when: item.upg and item.image is defined

    - name: Ensure git deployment key(s) is in place
      copy:
        src: "{{ item.key }}"
        dest: /opt/csc/{{ item.key }}
        mode: 0600
      with_items: "{{ docker_projects }}"
      when: item.upg and item.key is defined

    - name: Ensure docker project(s) is checked out
      git:
        repo: git@github.csc.com:Automation/{{ item.name }}.git
        dest: /opt/csc/src/{{ item.name }}
        force: yes
        key_file: /opt/csc/{{ item.key }}
        accept_hostkey: yes
      with_items: "{{ docker_projects }}"
      when: item.upg and item.key is defined

    - name: Checkout the latest tagged version
      shell: "git checkout $(git describe --abbrev=0 --tags)"
      args:
        chdir: "/opt/csc/src/docker-mediacascade"
      register: git_mediacascade

    - name: Debug Git checkout of docker-mediacascade
      debug:
        var: git_mediacascade

    - name: Check if slmzsync Docker image exists
      docker_image_facts:
        name: slmzsync
      register: slmzsync_image

    - debug:
        var: slmzsync_image

#    - name: Remove existing slmzsync Docker image
#      docker_image:
#        name: slmzsync
#        state: absent
#        force: yes
#      when: "{{ slmzsync_image.images | length > 0 }}"














#  - name: Check if slmzsync Docker image exists
#    docker_image_facts:
#      name: slmzsync
#    register: slmzsync_image

#  - debug:
#      var: slmzsync_image

#  - name: Remove existing slmzsync Docker image
#    docker_image:
#      name: slmzsync
#      state: absent
#      force: yes
#    when: "{{ slmzsync_image.images | length > 0 }}"

#  - name: Build slmzsync Docker image
#    docker_image:
#      name: "slmzsync"
#      path: "/opt/csc/src/docker-mediacascade"
#      pull: False
#    register: slmzsync
#    until: slmzsync|success
#    retries: 6
#    delay: 60

#       when: {{ item.upg }}

