---
#--------------------------------------------------
# This playbook will upgrade the Docker containers on the CAM hosts
# based on the variables set
#--------------------------------------------------

- name: Upgrade CAM host Docker Containers
  hosts: localhost
  gather_facts: true
  
  tasks:
  
  - name: Ensure docker-mediacascade git deployment key is in place
    copy:
      src: ./slm_mediacascade_ro_deployment_key_rsa
      dest: "/opt/csc/slm_mediacascade_ro_deployment_key_rsa"
      mode: 0600

  - name: Ensure docker-mediacascade project is checked out
    git:
      repo: "git@github.csc.com:Automation/docker-mediacascade.git"
      dest: "/opt/csc/src/docker-mediacascade"
      force: yes
      key_file: "/opt/csc/slm_mediacascade_ro_deployment_key_rsa"
      accept_hostkey: yes

  - name: Checkout the latest tagged version
    shell: "git checkout $(git describe --abbrev=0 --tags)"
    args:
      chdir: "/opt/csc/src/docker-mediacascade"

  - name: Git the tagged version
    shell: git describe --tags
    args:
      chdir: /opt/csc/src/docker-mediacascade
    register: git_tags

  - name: Show the git checkout of docker-mediacascade
    debug:
      var: git_tags

  - name: Get list of docker image tags present
    shell: docker images | grep "^slmzsync" | awk '{print $2;}'
    register: current_tags

  - name: Show the current image tags
    debug:
      var: current_tags

  - name: Remove existing image (force rebuild)
    docker_image:
      name: slmzsync
      tag: "{{ current_tags.stdout }}"
      state: absent
      force: yes
    when:
      - current_tags != ""
      - current_tags != git_tags

  - name: Ensure slmzsync image is built
    docker_image:
      name: slmzsync
      tag: "{{ git_tags.stdout }}"
      path: /opt/csc/src/docker-mediacascade
      pull: False
    register: new_image
    until: new_image|success
    retries: 3
    delay: 30
    when:
      - current_tags != git_tags

  - name: Show new image
    debug:
      var: new_image
