---
- name: Wait
  hosts: localhost
  gather_facts: true
  tasks:
  
  - name: Check for wait
    command: ps -ef | grep wait
    ignore_errors: true
    register: wait_for

  - debug:
      var: wait_for


  - name: Wait
    wait_for:
      port: 8000
      delay: 300
